### ISSUE TITLE
SSLException on running ./run ser --apis databind,stream --libs jackson

### ISSUE THREAD

**Issue by langelescu** [fabienrenaud/java-json-benchmark#36]
There is an issue with running the example command after installation.

> ./run ser --apis stream --libs jackson

.\gradlew clean build shadowJar
Downloading https://services.gradle.org/distributions/gradle-6.2.1-bin.zip

Exception in thread "main" javax.net.ssl.SSLException: Received fatal alert: protocol_version
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
        at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1979)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1086)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1332)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1359)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1343)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:78)
        at org.gradle.wrapper.Download.download(Download.java:63)
        at org.gradle.wrapper.Install$1.call(Install.java:68)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
java -server -XX:+AggressiveOpts -Xms2g -Xmx2g -jar build\libs\app.jar ser --apis stream --libs jackson
Error: Unable to access jarfile build\libs\app.jar

**Comment by fabienrenaud** [comment]
I don't have this issue on Mac and given you've opened another issue that requires the build to pass, I take you have resolved the problem. Closing.

**Comment by langelescu** [comment]
I did overcome the issue by applying the pull request that upgraded Gradle. I see you have merged it already so this issue is closed.
